#!/bin/sh

cmake .. \
	-DCMAKE_BUILD_TYPE=Release \
 	-DCMAKE_INSTALL_PREFIX=$PWD \
	-DBUILD_ZLIB=ON \
	-DBUILD_TIFF=ON \
	-DBUILD_JASPER=OFF \
	-DBUILD_JPEG=ON \
	-DBUILD_PNG=ON \
	-DBUILD_OPENEXR=OFF \
	-DBUILD_WEBP=OFF \
	-DBUILD_TBB=OFF \
	-DBUILD_IPP_IW=OFF \
	-DBUILD_ITT=OFF \
	-DBUILD_SHARED_LIBS=OFF \
	-DBUILD_opencv_apps=OFF \
	-DBUILD_opencv_js=OFF \
	-DBUILD_ANDROID_PROJECTS=OFF \
	-DBUILD_ANDROID_EXAMPLES=OFF \
	-DBUILD_DOCS=OFF \
	-DBUILD_EXAMPLES=OFF \
	-DBUILD_PACKAGE=OFF \
	-DBUILD_PERF_TESTS=OFF \
	-DBUILD_TESTS=OFF \
	-DBUILD_WITH_DEBUG_INFO=OFF \
	-DBUILD_WITH_STATIC_CRT=OFF \
	-DBUILD_WITH_DYNAMIC_IPP=OFF \
	-DBUILD_FAT_JAVA_LIB=OFF \
	-DBUILD_ANDROID_SERVICE=OFF \
	-DBUILD_CUDA_STUBS=OFF \
	-DBUILD_JAVA=OFF \
	-DBUILD_opencv_calib3d=OFF \
	-DBUILD_opencv_features2d=OFF \
	-DBUILD_opencv_flann=OFF \
	-DBUILD_opencv_flann=OFF \
	-DBUILD_opencv_highgui=OFF \
	-DBUILD_opencv_ml=OFF \
	-DBUILD_opencv_objdetect=OFF \
	-DBUILD_opencv_photo=OFF \
	-DBUILD_opencv_shape=OFF \
	-DBUILD_opencv_stitching=OFF \
	-DBUILD_opencv_superres=OFF \
	-DBUILD_opencv_ts=OFF \
	-DBUILD_opencv_video=OFF \
	-DBUILD_opencv_videoio=OFF \
	-DBUILD_opencv_videostab=OFF \
	-DBUILD_opencv_world=OFF \
	-DWITH_1394=OFF \
    -DWITH_AVFOUNDATION=OFF \
	-DWITH_CARBON=OFF \
	-DWITH_CAROTENE=OFF \
	-DWITH_CPUFEATURES=OFF \
	-DWITH_VTK=OFF \
	-DWITH_CUDA=OFF \
	-DWITH_CUFFT=OFF \
	-DWITH_CUBLAS=OFF \
	-DWITH_NVCUVID=OFF \
	-DWITH_EIGEN=OFF \
	-DWITH_VFW=OFF \
	-DWITH_FFMPEG=OFF \
	-DWITH_GSTREAMER=OFF \
	-DWITH_GSTREAMER_0_10=OFF \
	-DWITH_GTK=OFF \
	-DWITH_GTK_2_X=OFF \
	-DWITH_IPP=OFF \
	-DWITH_HALIDE=OFF \
	-DWITH_INF_ENGINE=OFF \
	-DWITH_NGRAPH=OFF \
	-DWITH_JASPER=OFF \
	-DWITH_JPEG=ON \
	-DWITH_WEBP=OFF \
	-DWITH_OPENEXR=OFF \
	-DWITH_OPENGL=OFF \
	-DWITH_OPENGL=OFF \
	-DWITH_OPENNI=OFF \
	-DWITH_OPENNI2=OFF \
	-DWITH_PNG=ON \
	-DWITH_GDCM=OFF \
	-DWITH_PVAPI=OFF \
	-DWITH_GIGEAPI=OFF \
	-DWITH_ARAVIS=OFF \
	-DWITH_QT=OFF \
	-DWITH_WIN32UI=OFF \
	-DWITH_QUICKTIME=OFF \
	-DWITH_QTKIT=OFF \
	-DWITH_TBB=OFF \
	-DWITH_OPENMP=OFF \
	-DWITH_CSTRIPES=OFF \
	-DWITH_PTHREADS_PF=OFF \
	-DWITH_TIFF=ON \
	-DWITH_UNICAP=OFF \
	-DWITH_V4L=OFF \
	-DWITH_LIBV4L=OFF \
	-DWITH_DSHOW=OFF \
	-DWITH_MSMF=OFF \
	-DWITH_MSMF_DXVA=OFF \
	-DWITH_XIMEA=OFF \
	-DWITH_XINE=OFF \
	-DWITH_CLP=OFF \
	-DWITH_OPENCL=OFF \
	-DWITH_OPENCL_SVM=OFF \
	-DWITH_OPENCLAMDFFT=OFF \
	-DWITH_OPENCLAMDBLAS=OFF \
	-DWITH_DIRECTX=OFF \
	-DWITH_OPENCL_D3D11_NV=OFF \
	-DWITH_INTELPERC=OFF \
	-DWITH_VA=OFF \
	-DWITH_VA_INTEL=OFF \
	-DWITH_MFX=OFF \
	-DWITH_GDAL=OFF \
	-DWITH_GPHOTO2=OFF \
	-DWITH_LAPACK=OFF \
	-DWITH_ITT=OFF \
	-DWITH_PROTOBUF=OFF \
	-DWITH_IMGCODEC_HDR=OFF \
	-DWITH_IMGCODEC_SUNRASTER=OFF \
	-DWITH_IMGCODEC_PXM=OFF \
	-DWITH_QUIRC=OFF \
	-DWITH_TENGINE=OFF \
	-DCMAKE_C_FLAGS="-Wl,--gc-sections,--no-whole-archive -Os -ffunction-sections -fdata-sections -Wl,--gc-sections,--no-whole-archive" \
 	-DCMAKE_CXX_FLAGS="-Wl,--gc-sections,--no-whole-archive -Os -ffunction-sections -fdata-sections -Wl,--gc-sections,--no-whole-archive"














